### ISSUE TITLE
如何一步导出到word或pdf

### ISSUE THREAD

**Issue by fredericky123** [cuiguojie/wechat2html#1]
如何包含图片地一步生成pdf或word呢

**Comment by cuiguojie** [comment]
@fredericky123 这个本来是我写给公司运营不熟悉HTML的同事用的小工具，他们相同的公告要在微信和网站各发一遍相当麻烦。

你的一步导出，是要把微信文档页整页导出，还是像工具里只导内容部分？以及，导出的排版是用自家的CSS还是微信那边的？

**Comment by fredericky123** [comment]
非常感谢您的回复！需求是保持微信的排版，将公众号内容保存为pdf,最好是word，而且图片能保持下来。非常非常感谢！

**Comment by cuiguojie** [comment]
@fredericky123 
在PDF上高度精确还原网页排版我不确定能不能实现，毕竟网页里有各种奇怪的内外边距、字体、加粗、文本色之类设置。

最简单的是像那些山寨电子书一样，整张网页截图生成图片，然后插入PDF。不过这样的话，PDF里的文本无法复制粘贴和编辑

**Comment by fredericky123** [comment]
是的，直接截图生成图片有点太粗糙了，大神有空就搞搞看，没有空闲搞也就算啦

**Comment by cuiguojie** [comment]
@fredericky123 

试了下，已经有轮子了， https://www.npmjs.com/package/chrome-headless-render-pdf

只不过微信那边做了懒加载，直接用这工具的话只能加载第一屏的图片。

现在没功夫做这个功能，先写个跳板，把懒加载的图片地址给补成真实地址。代码在 wechat2pfd 分支

你的流程需要：

1.  本机安装chrome的工具
```npm i chrome-headless-render-pdf -g```

2.  运行我这个转发程序 注意是 ```wechat2pdf```分支的代码
```npm run start```

3. 本机转换
```chrome-headless-render-pdf --url http://localhost:3000/api/\?url\=https://mp.weixin.qq.com/s/DPD4-WfeTJzDAbsjzBUIqQ --pdf abc.pdf```

其实就是在微信公众号的网页地址前面加 ```http://localhost:3000/api/?url=``` 去做个反向代理。

chrome-headless-render-pdf 的命令格式直接看文档即可，注意 ```--url``` 里的```？``` 和 ```=``` 要转义

**Comment by fredericky123** [comment]
厉害了
