### ISSUE TITLE
链接中含有视频怎么解决

### ISSUE THREAD

**Issue by timeend123** [cuiguojie/wechat2html#5]

**Comment by cuiguojie** [comment]
@timeend123 

大致翻了下，视频文章的 DOM 结构和普通图文的不同。

视频分几种情况，有的是微信直接上传，有的是引用第三方网站。嵌入第三方网站的可以做到原样 iframe 输出，但是考虑到“防盗链”之类不可控的来源设定的话，显示出来也大概率无法使用吧

相比起来视频区 DOM 结构不同的辨别反倒好处理了

**Comment by timeend123** [comment]
是的,仔细对比了一下浏览器直接访问和引用后访问的dom结构，发现少了<video>标签，所以视频是无法播放的，暂时还没找到好多方案，不知作者有何好的方案
